name: PokeSnaps
favicon: null
layout_spectrum: 0
typography_spectrum: 0.11003
title: 'PokeSnaps - Level Up your pics '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f70000'
    - '#ffffff'
    - '#000000'
    - '#535353'
    - '#fc9999'
  brandStrength: 0.75
  lightness: 0.8125
  saturation: 0.08886049198918045
  rhythmicContrast: 0.5
purpose: []
