name: PokeSnaps
favicon: null
layout_spectrum: 0.724700792459771
typography_spectrum: 0.35042647761292756
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f70000'
    - '#ffffff'
    - '#000000'
    - '#535353'
    - '#fc9999'
  brandStrength: 0.375
  lightness: 0.10179060278460383
  saturation: 0.08886049198918045
  rhythmicContrast: 0.25
purpose: []
